# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(1120, 630)
        LoginDialog.setStyleSheet("background-color: rgb(241, 242, 246);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(LoginDialog)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.left_widget = QtWidgets.QWidget(LoginDialog)
        self.left_widget.setMinimumSize(QtCore.QSize(374, 425))
        self.left_widget.setMaximumSize(QtCore.QSize(374, 425))
        self.left_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.left_widget.setObjectName("left_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.left_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inner_widget = QtWidgets.QWidget(self.left_widget)
        self.inner_widget.setMaximumSize(QtCore.QSize(290, 244))
        self.inner_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inner_widget.setStyleSheet("QLineEdit{\n"
"border: 1px solid #3085FE;\n"
"border-radius:10px;}\n"
"QPushButton{\n"
"border-radius:10px;\n"
"}")
        self.inner_widget.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.inner_widget.setObjectName("inner_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inner_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.id_lab = QtWidgets.QLabel(self.inner_widget)
        self.id_lab.setMaximumSize(QtCore.QSize(290, 20))
        self.id_lab.setObjectName("id_lab")
        self.verticalLayout.addWidget(self.id_lab)
        self.id_lineedit = QtWidgets.QLineEdit(self.inner_widget)
        self.id_lineedit.setMaximumSize(QtCore.QSize(290, 40))
        self.id_lineedit.setStyleSheet("")
        self.id_lineedit.setObjectName("id_lineedit")
        self.verticalLayout.addWidget(self.id_lineedit)
        self.pw_lab = QtWidgets.QLabel(self.inner_widget)
        self.pw_lab.setMaximumSize(QtCore.QSize(290, 20))
        self.pw_lab.setObjectName("pw_lab")
        self.verticalLayout.addWidget(self.pw_lab)
        self.pw_lineedit = QtWidgets.QLineEdit(self.inner_widget)
        self.pw_lineedit.setMaximumSize(QtCore.QSize(290, 40))
        self.pw_lineedit.setObjectName("pw_lineedit")
        self.verticalLayout.addWidget(self.pw_lineedit)
        self.login_btn = QtWidgets.QPushButton(self.inner_widget)
        self.login_btn.setMaximumSize(QtCore.QSize(290, 40))
        self.login_btn.setStyleSheet("background-color: rgb(238, 239, 240);")
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout.addWidget(self.login_btn)
        self.face_check_btn = QtWidgets.QPushButton(self.inner_widget)
        self.face_check_btn.setMaximumSize(QtCore.QSize(290, 40))
        self.face_check_btn.setStyleSheet("background-color: rgb(48, 133, 254);")
        self.face_check_btn.setObjectName("face_check_btn")
        self.verticalLayout.addWidget(self.face_check_btn)
        self.horizontalLayout_2.addWidget(self.inner_widget)
        self.horizontalLayout.addWidget(self.left_widget)
        self.right_widget = QtWidgets.QWidget(LoginDialog)
        self.right_widget.setMinimumSize(QtCore.QSize(596, 0))
        self.right_widget.setMaximumSize(QtCore.QSize(596, 425))
        self.right_widget.setObjectName("right_widget")
        self.sample_lab = QtWidgets.QLabel(self.right_widget)
        self.sample_lab.setGeometry(QtCore.QRect(180, 150, 261, 111))
        self.sample_lab.setObjectName("sample_lab")
        self.horizontalLayout.addWidget(self.right_widget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Dialog"))
        self.id_lab.setText(_translate("LoginDialog", "ID"))
        self.pw_lab.setText(_translate("LoginDialog", "Password"))
        self.login_btn.setText(_translate("LoginDialog", "로그인하기"))
        self.face_check_btn.setText(_translate("LoginDialog", "얼굴인식"))
        self.sample_lab.setText(_translate("LoginDialog", "여기에 얼굴인식 화면이 들어갑니다"))
