# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWidget(object):
    def setupUi(self, LoginWidget):
        LoginWidget.setObjectName("LoginWidget")
        LoginWidget.resize(1120, 630)
        LoginWidget.setMinimumSize(QtCore.QSize(1120, 630))
        LoginWidget.setMaximumSize(QtCore.QSize(1120, 630))
        LoginWidget.setStyleSheet("background-color: rgb(241, 242, 246);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(LoginWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.left_widget = QtWidgets.QWidget(LoginWidget)
        self.left_widget.setMinimumSize(QtCore.QSize(374, 425))
        self.left_widget.setMaximumSize(QtCore.QSize(374, 425))
        self.left_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.left_widget.setObjectName("left_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.left_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inner_widget = QtWidgets.QWidget(self.left_widget)
        self.inner_widget.setMaximumSize(QtCore.QSize(290, 277))
        self.inner_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inner_widget.setStyleSheet("QLineEdit{\n"
"border: 1px solid #3085FE;\n"
"border-radius:10px;}\n"
"QPushButton{\n"
"border-radius:10px;\n"
"}")
        self.inner_widget.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.inner_widget.setObjectName("inner_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inner_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.id_lab = QtWidgets.QLabel(self.inner_widget)
        self.id_lab.setMaximumSize(QtCore.QSize(290, 20))
        self.id_lab.setObjectName("id_lab")
        self.verticalLayout.addWidget(self.id_lab)
        self.id_lineedit = QtWidgets.QLineEdit(self.inner_widget)
        self.id_lineedit.setMaximumSize(QtCore.QSize(290, 40))
        self.id_lineedit.setStyleSheet("")
        self.id_lineedit.setObjectName("id_lineedit")
        self.verticalLayout.addWidget(self.id_lineedit)
        self.pw_lab = QtWidgets.QLabel(self.inner_widget)
        self.pw_lab.setMaximumSize(QtCore.QSize(290, 20))
        self.pw_lab.setObjectName("pw_lab")
        self.verticalLayout.addWidget(self.pw_lab)
        self.pw_lineedit = QtWidgets.QLineEdit(self.inner_widget)
        self.pw_lineedit.setMaximumSize(QtCore.QSize(290, 40))
        self.pw_lineedit.setObjectName("pw_lineedit")
        self.verticalLayout.addWidget(self.pw_lineedit)
        self.login_btn = QtWidgets.QPushButton(self.inner_widget)
        self.login_btn.setMaximumSize(QtCore.QSize(290, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("background-color: rgb(238, 239, 240);")
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout.addWidget(self.login_btn)
        self.face_check_btn = QtWidgets.QPushButton(self.inner_widget)
        self.face_check_btn.setMaximumSize(QtCore.QSize(290, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.face_check_btn.setFont(font)
        self.face_check_btn.setStyleSheet("background-color: rgb(48, 133, 254);\n"
"color: rgb(255, 255, 255);")
        self.face_check_btn.setObjectName("face_check_btn")
        self.verticalLayout.addWidget(self.face_check_btn)
        self.horizontalLayout_2.addWidget(self.inner_widget)
        self.horizontalLayout.addWidget(self.left_widget)
        self.right_widget = QtWidgets.QWidget(LoginWidget)
        self.right_widget.setMinimumSize(QtCore.QSize(596, 0))
        self.right_widget.setMaximumSize(QtCore.QSize(596, 425))
        self.right_widget.setObjectName("right_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.right_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.right_widget)
        self.widget.setMaximumSize(QtCore.QSize(375, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.face_lab = QtWidgets.QLabel(self.widget)
        self.face_lab.setMinimumSize(QtCore.QSize(356, 356))
        self.face_lab.setMaximumSize(QtCore.QSize(356, 356))
        self.face_lab.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.face_lab.setText("")
        self.face_lab.setPixmap(QtGui.QPixmap(":/face-id.png"))
        self.face_lab.setScaledContents(True)
        self.face_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.face_lab.setObjectName("face_lab")
        self.verticalLayout_3.addWidget(self.face_lab)
        self.explain_lab = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.explain_lab.setFont(font)
        self.explain_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.explain_lab.setObjectName("explain_lab")
        self.verticalLayout_3.addWidget(self.explain_lab)
        self.horizontalLayout_3.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.right_widget)
        spacerItem1 = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(LoginWidget)
        QtCore.QMetaObject.connectSlotsByName(LoginWidget)

    def retranslateUi(self, LoginWidget):
        _translate = QtCore.QCoreApplication.translate
        LoginWidget.setWindowTitle(_translate("LoginWidget", "Form"))
        self.id_lab.setText(_translate("LoginWidget", "ID"))
        self.pw_lab.setText(_translate("LoginWidget", "Password"))
        self.login_btn.setText(_translate("LoginWidget", "로그인하기"))
        self.face_check_btn.setText(_translate("LoginWidget", "얼굴인식"))
        self.explain_lab.setText(_translate("LoginWidget", "얼굴인식 버튼을 클릭해 주세요!"))
from Main.UI import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWidget = QtWidgets.QWidget()
    ui = Ui_LoginWidget()
    ui.setupUi(LoginWidget)
    LoginWidget.show()
    sys.exit(app.exec_())
