# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenWidget(object):
    def setupUi(self, OpenWidget):
        OpenWidget.setObjectName("OpenWidget")
        OpenWidget.resize(1120, 630)
        self.verticalLayout = QtWidgets.QVBoxLayout(OpenWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(OpenWidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/open_page.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(OpenWidget)
        QtCore.QMetaObject.connectSlotsByName(OpenWidget)

    def retranslateUi(self, OpenWidget):
        _translate = QtCore.QCoreApplication.translate
        OpenWidget.setWindowTitle(_translate("OpenWidget", "Form"))
from Main.UI import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OpenWidget = QtWidgets.QWidget()
    ui = Ui_OpenWidget()
    ui.setupUi(OpenWidget)
    OpenWidget.show()
    sys.exit(app.exec_())
