# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SaveUserImg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveUserImg(object):
    def setupUi(self, SaveUserImg):
        SaveUserImg.setObjectName("SaveUserImg")
        SaveUserImg.resize(1063, 567)
        SaveUserImg.setStyleSheet("background-color: rgb(241, 242, 246);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SaveUserImg)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_widget = QtWidgets.QWidget(SaveUserImg)
        self.top_widget.setMinimumSize(QtCore.QSize(0, 116))
        self.top_widget.setMaximumSize(QtCore.QSize(16777215, 116))
        self.top_widget.setStyleSheet("\n"
"QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 3px;\n"
"}\n"
"")
        self.top_widget.setObjectName("top_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.top_vlay = QtWidgets.QVBoxLayout()
        self.top_vlay.setObjectName("top_vlay")
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.top_vlay.addItem(spacerItem1)
        self.widget_11 = QtWidgets.QWidget(self.top_widget)
        self.widget_11.setMaximumSize(QtCore.QSize(290, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.widget_11.setFont(font)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.title_lab = QtWidgets.QPushButton(self.widget_11)
        self.title_lab.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.title_lab.setFont(font)
        self.title_lab.setObjectName("title_lab")
        self.horizontalLayout_12.addWidget(self.title_lab)
        self.top_vlay.addWidget(self.widget_11)
        self.horizontalLayout_2.addLayout(self.top_vlay)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.top_widget)
        self.main_widget = QtWidgets.QWidget(SaveUserImg)
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(323, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.widget = QtWidgets.QWidget(self.main_widget)
        self.widget.setMinimumSize(QtCore.QSize(0, 440))
        self.widget.setStyleSheet("QLineEdit{\n"
"height: 40px;\n"
"}\n"
"QComboBox{\n"
"height: 40px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 20, 0, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_img = QtWidgets.QLabel(self.widget)
        self.user_img.setMinimumSize(QtCore.QSize(500, 323))
        self.user_img.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.user_img.setAlignment(QtCore.Qt.AlignCenter)
        self.user_img.setObjectName("user_img")
        self.verticalLayout.addWidget(self.user_img)
        self.numimglabel = QtWidgets.QLabel(self.widget)
        self.numimglabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numimglabel.setObjectName("numimglabel")
        self.verticalLayout.addWidget(self.numimglabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem4)
        self.bottom_widget = QtWidgets.QWidget(self.widget)
        self.bottom_widget.setMinimumSize(QtCore.QSize(0, 60))
        self.bottom_widget.setMaximumSize(QtCore.QSize(16777215, 440))
        self.bottom_widget.setObjectName("bottom_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bottom_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.capture_btn = QtWidgets.QPushButton(self.bottom_widget)
        self.capture_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.capture_btn.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.capture_btn.setFont(font)
        self.capture_btn.setStyleSheet("background-color: rgb(48, 133, 254);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.capture_btn.setObjectName("capture_btn")
        self.horizontalLayout.addWidget(self.capture_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.bottom_widget)
        self.cancel_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.cancel_btn.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius:10px;")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.verticalLayout.addWidget(self.bottom_widget)
        self.horizontalLayout_3.addWidget(self.widget)
        spacerItem5 = QtWidgets.QSpacerItem(322, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.main_widget)

        self.retranslateUi(SaveUserImg)
        QtCore.QMetaObject.connectSlotsByName(SaveUserImg)

    def retranslateUi(self, SaveUserImg):
        _translate = QtCore.QCoreApplication.translate
        SaveUserImg.setWindowTitle(_translate("SaveUserImg", "Form"))
        self.title_lab.setText(_translate("SaveUserImg", "얼굴 등록 화면"))
        self.user_img.setText(_translate("SaveUserImg", "사진촬영을 눌러주세요!"))
        self.numimglabel.setText(_translate("SaveUserImg", "캡쳐된 이미지 수"))
        self.capture_btn.setText(_translate("SaveUserImg", "사진촬영"))
        self.cancel_btn.setText(_translate("SaveUserImg", "취소"))
from Main.UI import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaveUserImg = QtWidgets.QWidget()
    ui = Ui_SaveUserImg()
    ui.setupUi(SaveUserImg)
    SaveUserImg.show()
    sys.exit(app.exec_())
