# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserCell.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(250, 100)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(250, 100))
        self.frame.setMaximumSize(QtCore.QSize(250, 100))
        self.frame.setStyleSheet("#frame{\n"
"        background-color: rgb(255, 255, 255);\n"
"        border-radius:10px;\n"
"            }")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(166, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setMaximumSize(QtCore.QSize(156, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.img_lab = QtWidgets.QLabel(self.widget)
        self.img_lab.setMinimumSize(QtCore.QSize(50, 50))
        self.img_lab.setMaximumSize(QtCore.QSize(50, 50))
        self.img_lab.setStyleSheet("")
        self.img_lab.setObjectName("img_lab")
        self.horizontalLayout_4.addWidget(self.img_lab)
        self.name_lab = QtWidgets.QLabel(self.widget)
        self.name_lab.setObjectName("name_lab")
        self.horizontalLayout_4.addWidget(self.name_lab)
        self.horizontalLayout_2.addWidget(self.widget)
        self.del_btn = QtWidgets.QPushButton(self.frame_2)
        self.del_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.del_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.del_btn.setStyleSheet("#close_btn::hover{\n"
"border: 1px solid #3C82F2;\n"
"    background-color: transparent;\n"
"}")
        self.del_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/interface.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_btn.setIcon(icon)
        self.del_btn.setIconSize(QtCore.QSize(40, 40))
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout_2.addWidget(self.del_btn)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.img_lab.setText(_translate("Form", "img"))
        self.name_lab.setText(_translate("Form", "name"))
from Main.UI import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
