# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarningDialog(object):
    def setupUi(self, WarningDialog):
        WarningDialog.setObjectName("WarningDialog")
        WarningDialog.resize(340, 370)
        WarningDialog.setStyleSheet("QFrame#frame{\n"
"border:1px solid rgb(45,45,45);\n"
"border-radius:20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(48, 133, 254);\n"
"    color:white;\n"
"    border-radius:10px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(WarningDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(WarningDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_widget = QtWidgets.QWidget(self.frame)
        self.top_widget.setObjectName("top_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon_lab = QtWidgets.QLabel(self.top_widget)
        self.icon_lab.setMinimumSize(QtCore.QSize(115, 115))
        self.icon_lab.setMaximumSize(QtCore.QSize(115, 115))
        self.icon_lab.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.icon_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_lab.setWordWrap(True)
        self.icon_lab.setObjectName("icon_lab")
        self.horizontalLayout.addWidget(self.icon_lab)
        self.verticalLayout_3.addWidget(self.top_widget)
        self.bottom_widget = QtWidgets.QWidget(self.frame)
        self.bottom_widget.setMaximumSize(QtCore.QSize(16777215, 130))
        self.bottom_widget.setObjectName("bottom_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom_widget)
        self.verticalLayout_2.setContentsMargins(11, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.warn_lab = QtWidgets.QLabel(self.bottom_widget)
        self.warn_lab.setMinimumSize(QtCore.QSize(0, 66))
        self.warn_lab.setMaximumSize(QtCore.QSize(16777215, 66))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.warn_lab.setFont(font)
        self.warn_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.warn_lab.setWordWrap(True)
        self.warn_lab.setObjectName("warn_lab")
        self.verticalLayout_2.addWidget(self.warn_lab)
        self.ok_btn = QtWidgets.QPushButton(self.bottom_widget)
        self.ok_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.ok_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ok_btn.setFont(font)
        self.ok_btn.setStyleSheet("")
        self.ok_btn.setObjectName("ok_btn")
        self.verticalLayout_2.addWidget(self.ok_btn)
        self.verticalLayout_3.addWidget(self.bottom_widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(WarningDialog)
        QtCore.QMetaObject.connectSlotsByName(WarningDialog)

    def retranslateUi(self, WarningDialog):
        _translate = QtCore.QCoreApplication.translate
        WarningDialog.setWindowTitle(_translate("WarningDialog", "Dialog"))
        self.icon_lab.setText(_translate("WarningDialog", "아이콘이 들어갑니다."))
        self.warn_lab.setText(_translate("WarningDialog", "경고문구가 들어갑니다."))
        self.ok_btn.setText(_translate("WarningDialog", "확인"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WarningDialog = QtWidgets.QDialog()
    ui = Ui_WarningDialog()
    ui.setupUi(WarningDialog)
    WarningDialog.show()
    sys.exit(app.exec_())
